import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

export type PdfProgramItem = {
  name: string;
  level: string;
  field: string;
  universityName: string;
  universityCountry: string;
  tuitionFee: number;
  tuitionCurrency: string;
  applicationFee: number | null;
  intakeDates: string[];
  visaRequired: boolean;
  courseDurationMonths: number | null;
  collegeRank: string | null;
  offerTurnaroundDays: number | null;
  eligibilityCriteria: string[];
};

export type PdfShortlist = {
  studentName: string;
  generatedAt: string;
  items: PdfProgramItem[];
};

export type PdfProgramDetail = PdfProgramItem & {
  requiredDocuments: string[];
  whyHighlights: string[];
  minGpa: number | null;
  location: string | null;
  generatedAt: string;
};

const BRAND = "#4f46e5";

// Client-facing brand used on every generated PDF. Override with
// PORTAL_BRAND_NAME (or NEXT_PUBLIC_APP_NAME) per deployment.
export const PDF_BRAND = process.env.PORTAL_BRAND_NAME ?? process.env.NEXT_PUBLIC_APP_NAME ?? "Global Study Advisory";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, color: "#0f172a", fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 },
  brand: { fontSize: 16, fontWeight: "bold", color: BRAND },
  meta: { fontSize: 8, color: "#64748b", textAlign: "right" },
  title: { fontSize: 13, fontWeight: "bold", marginBottom: 10 },
  row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  rowLeft: { flex: 1 },
  uni: { fontSize: 9, color: BRAND, fontWeight: "bold" },
  prog: { fontSize: 10, fontWeight: "bold" },
  sub: { fontSize: 8, color: "#64748b" },
  rightCol: { alignItems: "flex-end" },
  fee: { fontSize: 10, fontWeight: "bold" },
  sectionTitle: { fontSize: 11, fontWeight: "bold", marginTop: 14, marginBottom: 6, color: BRAND },
  line: { marginBottom: 3 },
  bold: { fontWeight: "bold" },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 7, color: "#94a3b8", textAlign: "center" },
});

function ProgramRow({ item }: { item: PdfProgramItem }) {
  return (
    <View style={styles.row}>
      <View style={styles.rowLeft}>
        <Text style={styles.uni}>{item.universityName} · {item.universityCountry}</Text>
        <Text style={styles.prog}>{item.name}</Text>
        <Text style={styles.sub}>
          {item.level} · {item.field}
          {item.courseDurationMonths ? ` · ${item.courseDurationMonths} months` : ""}
          {item.visaRequired ? " · visa required" : ""}
        </Text>
      </View>
      <View style={styles.rightCol}>
        <Text style={styles.fee}>{formatMoney(item.tuitionFee, item.tuitionCurrency)}</Text>
        {item.applicationFee != null && <Text style={styles.sub}>App fee {formatMoney(item.applicationFee, item.tuitionCurrency)}</Text>}
        {item.intakeDates.length > 0 && <Text style={styles.sub}>Intake: {item.intakeDates.map((d) => d.slice(0, 7)).join(", ")}</Text>}
      </View>
    </View>
  );
}

function formatMoney(amount: number, currency: string): string {
  return `${currency} ${amount.toLocaleString("en-MY", { maximumFractionDigits: 0 })}`;
}

export async function shortlistPdfBuffer(data: PdfShortlist): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>{PDF_BRAND}</Text>
          <Text style={styles.meta}>
            Prepared for {data.studentName}
            {"\n"}
            Generated {data.generatedAt}
          </Text>
        </View>
        <Text style={styles.title}>Personalised Shortlist — {data.items.length} courses</Text>
        {data.items.length === 0 ? (
          <Text style={styles.sub}>The shortlist is currently empty.</Text>
        ) : (
          data.items.map((it, i) => (
            <View key={i}>
              <Text style={styles.sub}>{`${i + 1}.`}</Text>
              <ProgramRow item={it} />
            </View>
          ))
        )}
        <Text style={styles.footer}>
          This shortlist was generated by your study-abroad consultant. Contact your agency for application details.
        </Text>
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}

export async function programPdfBuffer(data: PdfProgramDetail): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>{PDF_BRAND}</Text>
          <Text style={styles.meta}>Course factsheet · {data.generatedAt || data.universityName}</Text>
        </View>

        <Text style={styles.title}>{data.name}</Text>
        <Text style={[styles.uni, { marginBottom: 6 }]}>{data.universityName} · {data.universityCountry}</Text>

        <Text style={styles.sectionTitle}>Course at a glance</Text>
        <View>
          {[
            ["Level", data.level],
            ["Field", data.field],
            ["Location", data.location ?? "—"],
            ["Tuition fee", formatMoney(data.tuitionFee, data.tuitionCurrency)],
            ["Application fee", data.applicationFee != null ? formatMoney(data.applicationFee, data.tuitionCurrency) : "—"],
            ["Duration", data.courseDurationMonths ? `${data.courseDurationMonths} months` : "—"],
            ["College ranking", data.collegeRank ?? "—"],
            ["Offer turnaround", data.offerTurnaroundDays ? `~${data.offerTurnaroundDays} days` : "—"],
            ["Visa required", data.visaRequired ? "Yes" : "No"],
          ].map(([k, v], i) => (
            <View key={i} style={styles.line}>
              <Text>
                <Text style={styles.bold}>{k}: </Text>
                {v}
              </Text>
            </View>
          ))}
        </View>

        {data.intakeDates.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Upcoming intakes</Text>
            <Text style={styles.line}>{data.intakeDates.map((d) => d.slice(0, 10)).join("  ·  ")}</Text>
          </>
        )}

        {data.eligibilityCriteria.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Eligibility</Text>
            {data.eligibilityCriteria.map((c, i) => (
              <Text key={i} style={styles.line}>• {c}</Text>
            ))}
          </>
        )}

        {data.requiredDocuments.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Required documents</Text>
            {data.requiredDocuments.map((d, i) => (
              <Text key={i} style={styles.line}>• {d}</Text>
            ))}
          </>
        )}

        {data.whyHighlights.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Why choose this course</Text>
            {data.whyHighlights.map((h, i) => (
              <Text key={i} style={styles.line}>• {h}</Text>
            ))}
          </>
        )}

        <Text style={styles.footer}>
          Generated by {PDF_BRAND}. Figures are indicative; confirm with the university before applying.
        </Text>
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}

export type PdfBulkItem = {
  universityName: string;
  universityCountry: string;
  name: string;
  tuitionFee: number;
  tuitionCurrency: string;
  courseLanguage: string;
  durationMonths: number | null;
};

export type PdfBulk = {
  studentName: string;
  studentPhone: string;
  studentEmail: string;
  consultantName: string;
  generatedAt: string;
  items: PdfBulkItem[];
};

const bulkStyles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, color: "#0f172a", fontFamily: "Helvetica" },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: BRAND,
    color: "white",
    fontWeight: "bold",
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
});

export async function bulkProgramsPdfBuffer(data: PdfBulk): Promise<Buffer> {
  const cols = { fee: 62, lang: 52, dur: 56, cons: 70 } as const;
  const nameW = 528 - cols.fee - cols.lang - cols.dur - cols.cons;
  const cell = (w: number, text: string) => (
    <Text style={{ width: w, paddingRight: 4 }}>{text}</Text>
  );
  const doc = (
    <Document>
      <Page size="A4" style={bulkStyles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>{PDF_BRAND}</Text>
          <Text style={styles.meta}>
            Generated {data.generatedAt}
            {"\n"}
            Consultant: {data.consultantName}
          </Text>
        </View>
        <Text style={styles.title}>Course Selection — {data.items.length} programs</Text>
        <View style={{ marginBottom: 10 }}>
          <Text>Name: {data.studentName}</Text>
          <Text>Phone: {data.studentPhone || "—"}</Text>
          <Text>Email: {data.studentEmail || "—"}</Text>
        </View>
        <View style={bulkStyles.tableHeader}>
          {cell(nameW, "Course / University")}
          {cell(cols.fee, "Tuition")}
          {cell(cols.lang, "Language")}
          {cell(cols.dur, "Duration")}
          {cell(cols.cons, "Consultant")}
        </View>
        {data.items.map((it, i) => (
          <View key={i} style={bulkStyles.row} wrap={false}>
            {cell(nameW, `${it.name}\n${it.universityName}, ${it.universityCountry}`)}
            {cell(cols.fee, formatMoney(it.tuitionFee, it.tuitionCurrency))}
            {cell(cols.lang, it.courseLanguage)}
            {cell(cols.dur, it.durationMonths ? `${it.durationMonths} mo` : "—")}
            {cell(cols.cons, data.consultantName)}
          </View>
        ))}
        {data.items.length === 0 && <Text>No courses selected.</Text>}
        <Text style={styles.footer}>
          Prepared by {data.consultantName} via {PDF_BRAND}. Tuition fees are indicative; confirm with each university before applying.
        </Text>
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}